use_frameworks!

target 'UIKitExtensions_Example' do
  pod 'UIKitExtensions', :path => '../'

  target 'UIKitExtensions_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
